In [5]:
import pandas as pd
import numpy as np
import time

tabela = pd.read_csv('exemplo.csv')
NewTabela = tabela.sort_values(by=['Rajada'])
display(tabela)
display(NewTabela)



df = pd.DataFrame(NewTabela)
chegada = df['Chegada']
prioridade = df['Prioridade']
rajada = df['Rajada']

var = len(rajada)

rajaArr = [rajada]
chegArr = [chegada]
prioArr = [prioridade]

rajada = rajada.astype(np.int16)

start = time.time()

c=0
for c in range(rajada[2]):
    rajada[2] = rajada[2] - 1
    c += 1
    print(rajada[2])
    print('Tempo do processo: {}'.format(c))
    
    
b=0
for b in range(rajada[1]):
    rajada[1] = rajada[1] - 1
    b += 1
    print(rajada[1])
    print('Tempo do processo: {}'.format(b))
    
i=0
for h in range(rajada[8]):
    rajada[8] = rajada[8] - 1
    i += 1
    print(rajada[8])
    print('Tempo do processo: {}'.format(i))    
  

a=0
for a in range(rajada[0]):
    rajada[0] = rajada[0] - 1
    a += 1
    print(rajada[0])
    print('Tempo do processo: {}'.format(a))

e=0
for e in range(rajada[4]):
    rajada[4] = rajada[4] - 1
    e += 1
    print(rajada[4])
    print('Tempo do processo: {}'.format(e))    


g=0    
for g in range(rajada[6]):
    rajada[6] = rajada[6] - 1
    
    g += 1
    print(rajada[6])
    print('Tempo do processo: {}'.format(g))

 
    
h=0
for h in range(rajada[7]):
    rajada[7] = rajada[7] - 1
    h += 1
    print(rajada[7])
    print('Tempo do processo: {}'.format(h))
     

d=0
for d in range(rajada[3]):
    rajada[3] = rajada[3] - 1
    d += 1
    print(rajada[3])
    print('Tempo do processo: {}'.format(d))

f=0
for f in range(rajada[5]):
    rajada[5] = rajada[5] - 1
    f += 1
    print(rajada[5])
    print('Tempo do processo: {}'.format(f))       


tempoTotal = a+b+c+d+e+f+g
media = (a+b+c+d+e+f+g)/7
print('o tempo total de processamento é {}, O tempo médio é {}'.format(tempoTotal,media))

end = time.time()

print('Inicio: {}'.format(start))
print('Fechamento: {}'.format(end))
print(end - start)

   ID  Chegada  Rajada  Prioridade
0  P1        1       8           2
1  P2        1       3           1
2  P3        2       1           3
3  P4       10      15           5
4  P5       15       8           1
5  P6       20      20           2
6  P7       23       8           4
7  P8       30      14           3
8  P9       40       6           2

   ID  Chegada  Rajada  Prioridade
2  P3        2       1           3
1  P2        1       3           1
8  P9       40       6           2
0  P1        1       8           2
4  P5       15       8           1
6  P7       23       8           4
7  P8       30      14           3
3  P4       10      15           5
5  P6       20      20           2

0
Tempo do processo: 1
2
Tempo do processo: 1
1
Tempo do processo: 2
0
Tempo do processo: 3
5
Tempo do processo: 1
4
Tempo do processo: 2
3
Tempo do processo: 3
2
Tempo do processo: 4
1
Tempo do processo: 5
0
Tempo do processo: 6
7
Tempo do processo: 1
6
Tempo do processo: 2
5
Tempo do processo: 3
4
Tempo do processo: 4
3
Tempo do processo: 5
2
Tempo do processo: 6
1
Tempo do processo: 7
0
Tempo do processo: 8
7
Tempo do processo: 1
6
Tempo do processo: 2
5
Tempo do processo: 3
4
Tempo do processo: 4
3
Tempo do processo: 5
2
Tempo do processo: 6
1
Tempo do processo: 7
0
Tempo do processo: 8
7
Tempo do processo: 1
6
Tempo do processo: 2
5
Tempo do processo: 3
4
Tempo do processo: 4
3
Tempo do processo: 5
2
Tempo do processo: 6
1
Tempo do processo: 7
0
Tempo do processo: 8
13
Tempo do processo: 1
12
Tempo do processo: 2
11
Tempo do processo: 3
10
Tempo do processo: 4
9
Tempo do processo: 5
8
Tempo do processo: 6
7
Tempo do processo: 7
6
Tempo do processo: 8
5
Tempo do processo: 9
4
Tempo do processo: 10
3
Tempo do processo: 11
2
Tempo do processo: 12
1
Tempo do processo: 13
0
Tempo do processo: 14
14
Tempo do processo: 1
13
Tempo do processo: 2
12
Tempo do processo: 3
11
Tempo do processo: 4
10
Tempo do processo: 5
9
Tempo do processo: 6
8
Tempo do processo: 7
7
Tempo do processo: 8
6
Tempo do processo: 9
5
Tempo do processo: 10
4
Tempo do processo: 11
3
Tempo do processo: 12
2
Tempo do processo: 13
1
Tempo do processo: 14
0
Tempo do processo: 15
19
Tempo do processo: 1
18
Tempo do processo: 2
17
Tempo do processo: 3
16
Tempo do processo: 4
15
Tempo do processo: 5
14
Tempo do processo: 6
13
Tempo do processo: 7
12
Tempo do processo: 8
11
Tempo do processo: 9
10
Tempo do processo: 10
9
Tempo do processo: 11
8
Tempo do processo: 12
7
Tempo do processo: 13
6
Tempo do processo: 14
5
Tempo do processo: 15
4
Tempo do processo: 16
3
Tempo do processo: 17
2
Tempo do processo: 18
1
Tempo do processo: 19
0
Tempo do processo: 20
o tempo total de processamento é 63, O tempo médio é 9.0
Inicio: 1654906181.4259634
Fechamento: 1654906181.4409647
0.015001296997070312